"""Generate / merge .env — idempotent, never clobbers existing values."""

from __future__ import annotations

import os
import secrets
import sys
import tempfile
from pathlib import Path

from .platform_utils import REPO_ROOT, info, ok


def _parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    result: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        result[k.strip()] = v.strip()
    return result


def _write_env_atomic(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Memento — generated by ./install.sh",
        "# Safe to re-run: the installer preserves existing values.",
        "",
        "# ── required secrets ──",
    ]
    for key in [
        "MEMENTO_SECRET_KEY",
        "MEMENTO_COLLECTOR_TOKEN",
        "POSTGRES_PASSWORD",
        "MINIO_ROOT_USER",
        "MINIO_ROOT_PASSWORD",
    ]:
        lines.append(f"{key}={values.get(key, '')}")
    lines += ["", "# ── optional AI backends ──"]
    for key in [
        "ANTHROPIC_API_KEY",
        "MEMENTO_AI_API_KEY",
        "MEMENTO_AI_BASE_URL",
        "MEMENTO_AI_MODEL",
    ]:
        if key in values and values[key]:
            lines.append(f"{key}={values[key]}")
        else:
            lines.append(f"# {key}=")
    lines.append("")

    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".env.", text=True)
    try:
        os.write(fd, "\n".join(lines).encode("utf-8"))
        os.close(fd)
        os.replace(tmp, path)
        try:
            os.chmod(path, 0o600)
        except OSError:
            pass
    except Exception:
        os.close(fd) if fd else None
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def ensure_env(interactive: bool = True) -> dict[str, str]:
    """Ensure `.env` has all required secrets. Generate missing ones. Return merged dict."""
    env_path = REPO_ROOT / ".env"
    existing = _parse_env(env_path)
    merged = dict(existing)

    required = {
        "MEMENTO_SECRET_KEY": lambda: secrets.token_urlsafe(48),
        "MEMENTO_COLLECTOR_TOKEN": lambda: secrets.token_hex(32),
        "POSTGRES_PASSWORD": lambda: secrets.token_urlsafe(24),
        "MINIO_ROOT_USER": lambda: f"memento_{secrets.token_hex(4)}",
        "MINIO_ROOT_PASSWORD": lambda: secrets.token_urlsafe(24),
    }
    generated = []
    for key, gen in required.items():
        if not merged.get(key):
            merged[key] = gen()
            generated.append(key)

    if interactive:
        _prompt_optional(merged)

    _write_env_atomic(env_path, merged)
    if generated:
        ok(f".env generated new secrets: {', '.join(generated)}")
    else:
        ok(".env present (no regeneration needed)")
    return merged


def _prompt_optional(merged: dict[str, str]) -> None:
    prompts = [
        ("ANTHROPIC_API_KEY", "Anthropic API key (Claude, for AI daily summaries)"),
        ("MEMENTO_AI_API_KEY", "Alt AI API key (OpenAI-compatible, e.g. Aliyun Dashscope)"),
    ]
    any_asked = False
    for key, label in prompts:
        if merged.get(key):
            continue
        if not sys.stdin.isatty():
            continue
        any_asked = True
        try:
            val = input(f"  {label} [skip]: ").strip()
        except EOFError:
            val = ""
        if val:
            merged[key] = val
    if not any_asked:
        info("Skipping optional API key prompts (run again anytime to add them).")
